feat: messages config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
-echo "Checking for lint errors"
+#Processo de lint (busca por code smells) no código
+echo "Checking for linting errors..."
 npm run check ||
 (echo 'Linting errors encountered' && exit 1)
+echo "Lint check successfull"
 
-echo "Done"
+#Processo de Formatação do código
+echo "Formating project"
+npm run format ||
+(echo 'Format problems ocurred' && exit 1)
+echo "Format process ended"
+
+echo "Pre-commit stage is done"
